# Generated by Django 3.1.4 on 2020-12-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sonda',
            name='face',
            field=models.CharField(choices=[('C', 'C'), ('D', 'D'), ('B', 'B'), ('E', 'E')], default='D', max_length=1),
        ),
    ]
