# Generated by Django 3.1.4 on 2020-12-05 22:36

from django.db import migrations


def create_sonda(apps, schema_editor):
    Sonda = apps.get_model('core', 'Sonda')

    my_sonda = Sonda()
    my_sonda.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201205_1714'),
    ]

    operations = [
        migrations.RunPython(create_sonda)
    ]
